/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ask */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alternative */
        Alternative: {
            /**
             * Reason
             * @description How this table differs: universe, distribution versus median, collapsed table, race iteration, or related table.
             */
            reason: string;
            /**
             * Table Id
             * @description ACS table ID.
             */
            table_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @description The user's question. Leading and trailing whitespace is stripped.
             */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /**
             * Alternatives
             * @description Related tables with the reason they differ from the selection.
             */
            alternatives: components["schemas"]["Alternative"][];
            /**
             * Answer
             * @description Natural-language answer.
             */
            answer: string;
            /**
             * Attempted Years
             * @description Years for which a Census request was issued.
             */
            attempted_years: number[];
            /**
             * Failed Years
             * @description Attempted years that failed or timed out.
             */
            failed_years: number[];
            /**
             * Geoid
             * @description AFFGEOID of the selected geography; empty when many areas are returned.
             */
            geoid: string;
            /**
             * Legs
             * @description Per-year outcome in requested order, including failed legs.
             */
            legs: components["schemas"]["RequestLeg"][];
            /**
             * Moe
             * @description Per-row 90% margins, keyed to each estimate's matching M variable.
             */
            moe: {
                [key: string]: string | null;
            }[];
            /**
             * Omitted Years
             * @description Requested years that were not attempted.
             */
            omitted_years: number[];
            /**
             * Requested Years
             * @description Years asked of fetch_data, de-duplicated in first-requested order.
             */
            requested_years: number[];
            /**
             * Rows
             * @description Census rows as returned. Each row carries GEO_ID (AFFGEOID); empty when the row is a combined total rather than a published area.
             */
            rows: {
                [key: string]: string | null;
            }[];
            /**
             * Succeeded Years
             * @description Attempted years whose HTTP call succeeded.
             */
            succeeded_years: number[];
            /**
             * Table Id
             * @description Selected ACS table ID.
             */
            table_id: string;
            /**
             * Universe
             * @description Published universe of the selected table.
             */
            universe: string;
            /**
             * Urls
             * @description Key-redacted Census API URLs, one per attempted year, in requested order.
             */
            urls: string[];
            /**
             * Warnings
             * @description Non-blocking guards: overlapping_vintage, moe_not_significant, geography_unsupported, ambiguous_place, universe_mismatch, median_not_aggregatable, moe_aggregation_degraded, zcta_not_zip, geography_not_nested.
             */
            warnings: components["schemas"]["AskWarning"][];
        };
        /** AskWarning */
        AskWarning: {
            /**
             * Code
             * @description Machine-readable warning code.
             */
            code: string;
            /**
             * Detail
             * @description What was raised, in one sentence.
             */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RequestLeg */
        RequestLeg: {
            /**
             * Detail
             * @description Redacted reason when ok is false; empty on success.
             */
            detail: string;
            /**
             * Ok
             * @description Whether this HTTP call returned parseable rows.
             */
            ok: boolean;
            /**
             * Status Code
             * @description Census HTTP status; 0 on timeout or transport failure.
             */
            status_code: number;
            /**
             * Url
             * @description Key-redacted Census API URL for this year.
             */
            url: string;
            /**
             * Year
             * @description Vintage end year for this Census request.
             */
            year: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
