/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ask */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Conversation */
        post: operations["create_conversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{thread_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Turn */
        post: operations["append_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alternative */
        Alternative: {
            /**
             * Reason
             * @description How this table differs from the selection.
             */
            reason: string;
            /**
             * Table Id
             * @description ACS table ID.
             */
            table_id: string;
            /**
             * Title
             * @description Published table title.
             */
            title: string;
            /**
             * Universe
             * @description Published universe of this table.
             */
            universe: string;
        };
        /** AskRequest */
        AskRequest: {
            /** @description Optional typed override of table, years, geography, and overlapping ACS5. */
            plan?: components["schemas"]["ResultPlan"] | null;
            /**
             * Question
             * @description The user's question. Leading and trailing whitespace is stripped.
             */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /**
             * Alternatives
             * @description Related tables, with why they differ.
             */
            alternatives: components["schemas"]["Alternative"][];
            /**
             * Answer
             * @description Natural-language answer.
             */
            answer: string;
            /**
             * Attempted Years
             * @description Vintages a Census request was issued for.
             */
            attempted_years: number[];
            /** @description Validated chart roles, or null. */
            chart?: components["schemas"]["ChartSpec"] | null;
            /**
             * Chart Unavailable
             * @description Model chart failed validation.
             * @default false
             */
            chart_unavailable: boolean;
            /**
             * Comparisons
             * @description Paired estimates with MOE_diff.
             */
            comparisons: components["schemas"]["Comparison"][];
            /**
             * Failed Years
             * @description Attempted vintages that failed or timed out.
             */
            failed_years: number[];
            /**
             * Geoid
             * @description AFFGEOID of the selected geography; empty if many.
             */
            geoid: string;
            /**
             * Legs
             * @description Per-request outcome in requested order.
             */
            legs: components["schemas"]["RequestLeg"][];
            /**
             * Moe
             * @description Per-row 90% margins keyed to each M.
             */
            moe: {
                [key: string]: string | null;
            }[];
            /**
             * Omission Reasons
             * @description Reason code per omitted year.
             */
            omission_reasons: string[];
            /**
             * Omitted Years
             * @description Requested years that were not attempted.
             */
            omitted_years: number[];
            /** @description Executed table, years, and geographies for this answer. */
            plan: components["schemas"]["ResultPlan"];
            /**
             * Requested Years
             * @description Years asked of fetch_data.
             */
            requested_years: number[];
            /**
             * Rows
             * @description Census rows; each carries GEO_ID.
             */
            rows: {
                [key: string]: string | null;
            }[];
            /**
             * Succeeded Years
             * @description Attempted vintages that returned rows.
             */
            succeeded_years: number[];
            /**
             * Table Id
             * @description Selected ACS table ID.
             */
            table_id: string;
            /**
             * Universe
             * @description Published universe of the selected table.
             */
            universe: string;
            /**
             * Urls
             * @description Key-redacted Census API URLs, one per attempted request.
             */
            urls: string[];
            /**
             * Warnings
             * @description Non-blocking guards (docs/requirements.md).
             */
            warnings: components["schemas"]["AskWarning"][];
        };
        /** AskWarning */
        AskWarning: {
            /**
             * Candidates
             * @description Ranked executable geographies when code is ambiguous_place; else empty.
             */
            candidates?: components["schemas"]["GeoSpec"][];
            /**
             * Code
             * @description Machine-readable warning code.
             */
            code: string;
            /**
             * Detail
             * @description What was raised, in one sentence.
             */
            detail: string;
        };
        /**
         * ChartSpec
         * @description Roles over rows/moe. No duplicated data, Vega, or markup.
         */
        ChartSpec: {
            /**
             * Series By
             * @description Split by GEO_ID or estimate variable.
             */
            series_by?: ("geography" | "variable") | null;
            /**
             * Show Moe
             * @description MOE display cannot be opted out.
             * @default true
             * @constant
             */
            show_moe: true;
            /**
             * Title
             * @description Plain-text title.
             */
            title: string;
            /**
             * Type
             * @description line for years; bar for geographies.
             * @enum {string}
             */
            type: "line" | "bar";
            /**
             * X
             * @description Axis from row year or GEO_ID.
             * @enum {string}
             */
            x: "year" | "geography";
            /**
             * Y
             * @description Estimate columns; never copied values.
             * @constant
             */
            y: "estimate";
        };
        /** Comparison */
        Comparison: {
            /**
             * Distinguishable
             * @description True when abs(estimate_a - estimate_b) exceeds threshold.
             */
            distinguishable: boolean;
            /**
             * Estimate A
             * @description Published estimate for geoid_a.
             */
            estimate_a: string;
            /**
             * Estimate B
             * @description Published estimate for geoid_b.
             */
            estimate_b: string;
            /**
             * Geoid A
             * @description AFFGEOID of the first leg.
             */
            geoid_a: string;
            /**
             * Geoid B
             * @description AFFGEOID of the second leg.
             */
            geoid_b: string;
            /**
             * Moe A
             * @description 90% margin for estimate_a.
             */
            moe_a: string;
            /**
             * Moe B
             * @description 90% margin for estimate_b.
             */
            moe_b: string;
            /**
             * Shared Sample
             * @description True when the compared geographies nest and share ACS sample.
             */
            shared_sample: boolean;
            /**
             * Threshold
             * @description MOE_diff = sqrt(moe_a^2 + moe_b^2).
             */
            threshold: string;
            /**
             * Variable
             * @description Estimate variable compared.
             */
            variable: string;
            /**
             * Year
             * @description Vintage end year when both legs share one; else empty.
             */
            year: string;
        };
        /** Conversation */
        Conversation: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Title */
            title: string;
            /** Turns */
            turns: components["schemas"]["Turn"][];
        };
        /** ConversationInfo */
        ConversationInfo: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Title */
            title: string;
        };
        /**
         * GeoSpec
         * @description Executable geography. `for`/`in` come from metadata, not from prose.
         */
        GeoSpec: {
            /** Codes */
            codes?: {
                [key: string]: string;
            };
            /**
             * Dataset
             * @default acs5
             */
            dataset: string;
            /**
             * For Spec
             * @default
             */
            for_spec: string;
            /**
             * Geoid
             * @default
             */
            geoid: string;
            /**
             * In Spec
             * @default
             */
            in_spec: string;
            /**
             * Level
             * @default
             */
            level: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Vintage
             * @default 0
             */
            vintage: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RequestLeg */
        RequestLeg: {
            /**
             * Detail
             * @description Redacted reason when ok is false; empty on success.
             */
            detail: string;
            /**
             * For Spec
             * @description Census for= clause for this geography leg; empty when the built URL is used.
             * @default
             */
            for_spec: string;
            /**
             * Ok
             * @description Whether this HTTP call returned parseable rows.
             */
            ok: boolean;
            /**
             * Status Code
             * @description Census HTTP status; 0 on timeout or transport failure.
             */
            status_code: number;
            /**
             * Url
             * @description Key-redacted Census API URL for this year.
             */
            url: string;
            /**
             * Year
             * @description Vintage end year for this Census request.
             */
            year: number;
        };
        /**
         * ResultPlan
         * @description Executed table, variables, years, and geographies. Not extracted from prose.
         */
        ResultPlan: {
            /**
             * Allow Overlapping Acs5
             * @description Consecutive ACS5 explicitly allowed.
             * @default false
             */
            allow_overlapping_acs5: boolean;
            /**
             * Dataset
             * @description acs5 or acs1 actually requested.
             * @default acs5
             */
            dataset: string;
            /**
             * Geographies
             * @description Ordered resolved geos.
             */
            geographies?: components["schemas"]["GeoSpec"][];
            /**
             * Requested Years
             * @description Fetch request years.
             */
            requested_years?: number[];
            /**
             * Table Id
             * @description Selected ACS table ID.
             * @default
             */
            table_id: string;
            /**
             * Variables
             * @description Estimate IDs (E) from the URL.
             */
            variables?: string[];
            /**
             * Years
             * @description Vintages a request was issued for.
             */
            years?: number[];
        };
        /** Turn */
        Turn: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            plan: components["schemas"]["ResultPlan"] | null;
            /** Question */
            question: string;
            response: components["schemas"]["AskResponse"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description persistence unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_conversation: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description persistence unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    append_turn: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description conversation full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description persistence unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
