/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ask */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alternative */
        Alternative: {
            /**
             * Reason
             * @description How this table differs: universe, distribution versus median, collapsed table, race iteration, or related table.
             */
            reason: string;
            /**
             * Table Id
             * @description ACS table ID.
             */
            table_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @description The user's question. Leading and trailing whitespace is stripped.
             */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /**
             * Alternatives
             * @description Related tables with the reason they differ from the selection.
             */
            alternatives: components["schemas"]["Alternative"][];
            /**
             * Answer
             * @description Natural-language answer.
             */
            answer: string;
            /**
             * Attempted Years
             * @description Unique vintages for which a Census request was issued.
             */
            attempted_years: number[];
            /** @description Validated chart roles, or null. */
            chart?: components["schemas"]["ChartSpec"] | null;
            /**
             * Chart Unavailable
             * @description Model chart failed validation.
             * @default false
             */
            chart_unavailable: boolean;
            /**
             * Comparisons
             * @description Paired estimates with MOE_diff, 90% conclusion, and shared-sample flag.
             */
            comparisons: components["schemas"]["Comparison"][];
            /**
             * Failed Years
             * @description Unique attempted vintages with at least one failed or timed-out call.
             */
            failed_years: number[];
            /**
             * Geoid
             * @description AFFGEOID of the selected geography; empty when many areas are returned.
             */
            geoid: string;
            /**
             * Legs
             * @description Per-request outcome in requested order, including failed legs.
             */
            legs: components["schemas"]["RequestLeg"][];
            /**
             * Moe
             * @description Per-row 90% margins, keyed to each estimate's matching M variable.
             */
            moe: {
                [key: string]: string | null;
            }[];
            /**
             * Omission Reasons
             * @description Reason code per omitted year, same order as omitted_years.
             */
            omission_reasons: string[];
            /**
             * Omitted Years
             * @description Requested years that were not attempted.
             */
            omitted_years: number[];
            /**
             * Requested Years
             * @description Years asked of fetch_data, de-duplicated in first-requested order.
             */
            requested_years: number[];
            /**
             * Rows
             * @description Census rows as returned. Each row carries GEO_ID (AFFGEOID); empty when the row is a combined total rather than a published area.
             */
            rows: {
                [key: string]: string | null;
            }[];
            /**
             * Succeeded Years
             * @description Unique attempted vintages with at least one successful HTTP call.
             */
            succeeded_years: number[];
            /**
             * Table Id
             * @description Selected ACS table ID.
             */
            table_id: string;
            /**
             * Universe
             * @description Published universe of the selected table.
             */
            universe: string;
            /**
             * Urls
             * @description Key-redacted Census API URLs, one per attempted request, in requested order. When every requested vintage is omitted, this is the built URL so the request is still editable.
             */
            urls: string[];
            /**
             * Warnings
             * @description Non-blocking guards: overlapping_vintage, moe_not_significant, geography_unsupported, ambiguous_place, universe_mismatch, median_not_aggregatable, moe_aggregation_degraded, zcta_not_zip, geography_not_nested, acs1_geography_ineligible, vintage_gap_2020, boundary_change_2020, measure_unavailable, variable_not_in_vintage, shared_sample.
             */
            warnings: components["schemas"]["AskWarning"][];
        };
        /** AskWarning */
        AskWarning: {
            /**
             * Candidates
             * @description Ranked executable geographies when code is ambiguous_place; else empty.
             */
            candidates?: components["schemas"]["GeoSpec"][];
            /**
             * Code
             * @description Machine-readable warning code.
             */
            code: string;
            /**
             * Detail
             * @description What was raised, in one sentence.
             */
            detail: string;
        };
        /**
         * ChartSpec
         * @description Roles over rows/moe. No duplicated data, Vega, or markup.
         */
        ChartSpec: {
            /**
             * Series By
             * @description Split by GEO_ID or estimate variable.
             */
            series_by?: ("geography" | "variable") | null;
            /**
             * Show Moe
             * @description MOE display cannot be opted out.
             * @default true
             * @constant
             */
            show_moe: true;
            /**
             * Title
             * @description Plain-text title.
             */
            title: string;
            /**
             * Type
             * @description line for years; bar for geographies.
             * @enum {string}
             */
            type: "line" | "bar";
            /**
             * X
             * @description Axis from row year or GEO_ID.
             * @enum {string}
             */
            x: "year" | "geography";
            /**
             * Y
             * @description Estimate columns; never copied values.
             * @constant
             */
            y: "estimate";
        };
        /** Comparison */
        Comparison: {
            /**
             * Distinguishable
             * @description True when abs(estimate_a - estimate_b) exceeds threshold.
             */
            distinguishable: boolean;
            /**
             * Estimate A
             * @description Published estimate for geoid_a.
             */
            estimate_a: string;
            /**
             * Estimate B
             * @description Published estimate for geoid_b.
             */
            estimate_b: string;
            /**
             * Geoid A
             * @description AFFGEOID of the first leg.
             */
            geoid_a: string;
            /**
             * Geoid B
             * @description AFFGEOID of the second leg.
             */
            geoid_b: string;
            /**
             * Moe A
             * @description 90% margin for estimate_a.
             */
            moe_a: string;
            /**
             * Moe B
             * @description 90% margin for estimate_b.
             */
            moe_b: string;
            /**
             * Shared Sample
             * @description True when the compared geographies nest and share ACS sample.
             */
            shared_sample: boolean;
            /**
             * Threshold
             * @description MOE_diff = sqrt(moe_a^2 + moe_b^2).
             */
            threshold: string;
            /**
             * Variable
             * @description Estimate variable compared.
             */
            variable: string;
            /**
             * Year
             * @description Vintage end year when both legs share one; else empty.
             */
            year: string;
        };
        /**
         * GeoSpec
         * @description Executable geography. `for`/`in` come from metadata, not from prose.
         */
        GeoSpec: {
            /** Codes */
            codes?: {
                [key: string]: string;
            };
            /**
             * Dataset
             * @default acs5
             */
            dataset: string;
            /**
             * For Spec
             * @default
             */
            for_spec: string;
            /**
             * Geoid
             * @default
             */
            geoid: string;
            /**
             * In Spec
             * @default
             */
            in_spec: string;
            /**
             * Level
             * @default
             */
            level: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Vintage
             * @default 0
             */
            vintage: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RequestLeg */
        RequestLeg: {
            /**
             * Detail
             * @description Redacted reason when ok is false; empty on success.
             */
            detail: string;
            /**
             * For Spec
             * @description Census for= clause for this geography leg; empty when the built URL is used.
             * @default
             */
            for_spec: string;
            /**
             * Ok
             * @description Whether this HTTP call returned parseable rows.
             */
            ok: boolean;
            /**
             * Status Code
             * @description Census HTTP status; 0 on timeout or transport failure.
             */
            status_code: number;
            /**
             * Url
             * @description Key-redacted Census API URL for this year.
             */
            url: string;
            /**
             * Year
             * @description Vintage end year for this Census request.
             */
            year: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
